
filegroup(
    name = "test_images",
    srcs = glob(["*.png"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_results",
    srcs = glob(["*.npy"]),
    visibility = ["//visibility:public"],
)
